# Generated by Django 5.0.6 on 2026-06-04 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('second_device', 'Ikkinchi qurilma'), ('session_conflict', 'Sessiya konflikti'), ('root_detected', 'Root aniqlandi'), ('flag_secure_failed', "FLAG_SECURE o'rnatilmadi"), ('tamper', 'Buzish urinishi')], max_length=32, verbose_name='Turi')),
                ('detail', models.TextField(blank=True, verbose_name='Tafsilot')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP')),
                ('device_info', models.CharField(blank=True, max_length=255, verbose_name="Qurilma ma'lumoti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('action_taken', models.CharField(choices=[('logged', 'Faqat log'), ('session_blocked', 'Sessiya bloklandi')], default='logged', max_length=32, verbose_name="Ko'rilgan chora")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xavfsizlik signali',
                'verbose_name_plural': 'Xavfsizlik signallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
