# Generated by Django 5.0.6 on 2026-06-04 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('options', models.JSONField(default=list, verbose_name="Variantlar (ro'yxat)")),
                ('correct_index', models.PositiveIntegerField(verbose_name="To'g'ri javob indeksi")),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['test', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('time_limit_min', models.PositiveIntegerField(default=30, verbose_name='Vaqt chegarasi (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('current_question', models.PositiveIntegerField(default=0, verbose_name='Joriy savol indeksi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('finished', 'Tugagan'), ('void', 'Bekor qilingan')], default='active', max_length=16, verbose_name='Holat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Urinish',
                'verbose_name_plural': 'Urinishlar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.IntegerField(verbose_name='Tanlangan indeks')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt', verbose_name='Urinish')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='TestAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=16, verbose_name='Holat')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan")),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan admin")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='exams.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test ruxsati zayavkasi',
                'verbose_name_plural': 'Test ruxsati zayavkalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='testaccessrequest',
            constraint=models.UniqueConstraint(fields=('user', 'test'), name='uniq_user_test_request'),
        ),
    ]
